# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sentiment_pb2 as sentiment__pb2


class SentimentServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getAspects = channel.unary_unary(
        '/SentimentService/getAspects',
        request_serializer=sentiment__pb2.SentimentRequest.SerializeToString,
        response_deserializer=sentiment__pb2.SentimentResponse.FromString,
        )


class SentimentServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getAspects(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SentimentServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getAspects': grpc.unary_unary_rpc_method_handler(
          servicer.getAspects,
          request_deserializer=sentiment__pb2.SentimentRequest.FromString,
          response_serializer=sentiment__pb2.SentimentResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SentimentService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
